language: go
go:
  - 1.4
  - tip
matrix:
  allow_failures:
    - go: tip
before_install:
  - openssl aes-256-cbc -K $encrypted_9933eea0afad_key -iv $encrypted_9933eea0afad_iv -in integrationtest/acd-token.json.enc -out integrationtest/acd-token.json -d
  - chmod 0600 integrationtest/acd-token.json
  - go get -u golang.org/x/tools/cmd/cover
  - mkdir -p $GOPATH/src/gopkg.in && cd .. && mv ${TRAVIS_BUILD_DIR} $GOPATH/src/gopkg.in/acd.v0 && export TRAVIS_BUILD_DIR=$GOPATH/src/gopkg.in/acd.v0 && cd ${TRAVIS_BUILD_DIR}
script: go test -v -race -cover -bench=. ./...
